# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='date of food')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_text', models.CharField(max_length=200)),
                ('calorie_amount', models.IntegerField(default=0)),
                ('day_eaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_list.DailyFoodList')),
            ],
        ),
    ]
