# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day_eaten',
        ),
        migrations.AddField(
            model_name='dailyfoodlist',
            name='food_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_list.Food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='number_of_servings',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
