# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0002_auto_20170629_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfoodlist',
            name='food_text',
        ),
        migrations.AddField(
            model_name='dailyfoodlist',
            name='food_text',
            field=models.ManyToManyField(to='food_list.Food'),
        ),
    ]
