# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0003_auto_20170703_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfoodlist',
            name='entry_date',
            field=models.DateField(verbose_name='date of food'),
        ),
    ]
